[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install -y pkg-config libudev-dev:$CROSS_DEB_ARCH libssl-dev:$CROSS_DEB_ARCH libasound2-dev:$CROSS_DEB_ARCH",
]

[target.armv7-unknown-linux-gnueabihf.env]
passthrough = ["PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig"]